---
title: ".hand[What is a **facet**?]"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include = FALSE}
library(tidyverse)
library(gridExtra)
library(flair)

knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)
```


.larger[We've added a third variable with colors, shapes, and size...]

---

.larger[What is a **facet**?]

.pull-left[
.large[A *facet* is a subplot for each subset of a dataset.]
]

.pull-right[
```{r, echo = FALSE, fig.height = 10, fig.width = 12}
ggplot(data = mpg, 
       mapping = aes(x = displ,
                     y = hwy)) + 
  geom_point() + 
  geom_smooth() + 
  facet_wrap(~ class, nrow = 2)
```
]

---

.larger[We can facet by one variable with **facet_wrap()**]

</br>
</br>

<center>

```{r, eval = FALSE}
ggplot(data = mpg, 
       mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth() + 
  facet_wrap(~ class)
```

---

```{r, echo = FALSE, fig.align = 'center', fig.width = 10, fig.height = 8}
ggplot(data = mpg, 
       mapping = aes(x = displ,
                     y = hwy)) + 
  geom_point() + 
  geom_smooth() + 
  facet_wrap(~ class, nrow = 2)
```


---

.hand-medium[We can facet by two variables with **facet_grid()**]

</br>
</br>

<center>

```{r grid, eval = FALSE}
ggplot(data = mpg, 
       mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth() + 
  facet_grid(year ~ class)
```

---

```{r, echo = FALSE, fig.align = 'center', fig.width = 12, fig.height = 8}
ggplot(data = mpg, 
       mapping = aes(x = displ,
                     y = hwy)) + 
  geom_point() + 
  geom_smooth() + 
  facet_grid(year ~ class)
```

