---
title: ".hand[ggplot2 first steps]"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include = FALSE}
library(ggplot2)
```


```{r, fig.height = 6, fig.align='center'}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

---

.larger[Start with a blank plot]

```{r, fig.height = 5, fig.align='center'}
ggplot(data = mpg)
```

---

.larger[Add a `geom`]

```{r, eval = FALSE}
ggplot(data = mpg) + 
  geom_point()
```

---

.larger[Map variables to aesthetics]

```{r, fig.align='center', fig.height = 5}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

---

.larger[A reusable template

```{r, eval = FALSE}
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```

]