---
title: ".hand[How do I move ______ over there?]"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include = FALSE}
library(tidyverse)
library(gridExtra)
library(flair)

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 5, 
                      fig.height = 5, 
                      fig.align = "center")
```

.larger[You have control over *where* the bars go!]

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

```

---

.larger[Do you want them stacked?]

```{r stack, eval = FALSE}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), 
           position = "stack")

```

```{r}
decorate_chunk("stack", eval = TRUE, echo = TRUE) %>% 
  flair(pattern = 'position = "stack"')
```


---

.larger[Do you want them side-by-side?]

```{r dodge, eval = FALSE}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), 
           position = "dodge")

```

```{r}
decorate_chunk("dodge", eval = TRUE, echo = TRUE, fig.width = 8) %>% 
  flair(pattern = 'position = "dodge"')
```

---

.larger[Do you want to compare proportions?]

.pull-left[

</br>
</br>

```{r prop, eval = FALSE}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, 
                         fill = clarity), 
           position = "fill")

```

```{r}
decorate_chunk("prop", eval = FALSE, echo = TRUE) %>% 
  flair(pattern = 'position = "fill"')
```
]


.pull-right[
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut,
                         fill = clarity), 
           position = "fill")

```


]

---

.larger[Positions matter for scatterplots, too!]

```{r, fig.width = 5.5, fig.height = 5.5}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))

```

---

.larger[Jittering to eliminate overplotting]

```{r jitter, eval = FALSE}
ggplot(data = mpg) +
  geom_jitter(mapping = aes(x = displ, y = hwy))

```

```{r}
decorate_chunk("jitter", eval = TRUE, echo = TRUE, fig.width = 5.5, fig.height = 5.5) %>% 
  flair(pattern = "geom_jitter")
```



