---
title: "Challenge 7 -- Grading Guide"
output: html_document
---

## Vector Inputs

- Function accepts vector inputs & Visualization is great -- 10 points
- Function accepts vector inputs & Visualization is okay -- 9 points
- Function accepts vector inputs & Visualization is not good -- 8 points

*Function has generic (e.g., `x`, `y`, `variable1`, `variable2`) inputs that
do not indicate what variables are being used where -- 1 point deduction*

## Variable Name Inputs

- Function accepts variable names as inputs & Visualization is great -- 10.5 points
- Function accepts variable names as inputs & Visualization is okay -- 9.5 points
- Function accepts variable names as inputs & Visualization is not good -- 8.5 points

## Appears to Accept Variable Names but Actually Accepts Vector Inputs

- Function (deceptively) accepts vector inputs & Visualization is great -- 9.5 points
- Function (deceptively) accepts vector inputs & Visualization is okay -- 8.5 points
- Function (deceptively) accepts vector inputs & Visualization is not good -- 7.5 points
