---
title: "Model Selection `r emo::ji('bow and arrow')`"
date: "May 27, 2021"
author: "Stat 331"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r, include = FALSE}
knitr::opts_chunk$set(fig.align = "center")

options(htmltools.dir.version = FALSE)

library(xaringanthemer)
library(xaringan)
library(tidyverse)


style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)
```

class: inverse, middle, center

.hand-medium[I have a lot of variables, how do I choose a model?]

---

class: middle

.larger[Do you want to explain?]

--

> **Desire:** Describe and quantify the relationship between the outcome variable
> and a set of explanatory variables

--

- Determine the "significance" of relationships

- Identify causal relationships 


---

class: middle 

.larger[Do you want to predict?]

--

> **Desire:** Predict an outcome based on the information contained in
> a set of predictor variables

--

- Don’t care so much about understanding variable relationships

- Care about making good predictions


---

class: inverse, middle, center

.hand-medium[All models are wrong, but some are useful.]

.bitlarger[George Box, 1976]



---

.larger[Model Selection Criteria]

.pull-left[
- p-values 

- **adjusted $R^2$**

- SSE 

- RMSE
]

.pull-right[
- **AIC**

- BIC

- **Cross Validation**
]

---

class: center

.larger[What are the steps?]

.pull-left[
__1.__ Fit an initial model

__2.__ Add a variable (or interaction) to the model

__3.__ Compare models based on selection criteria
]

--

.pull-right[
__4.__ Keep the "better" model

$\vdots$

**Continue until all variables (and interactions) have been considered**

]


---

.larger[Model Selection **is not** Objective]

--

.pull-left[
.bitlarger[**Humans** define the "model set"]
]

--

.pull-right[
.bitlarger[**Humans** define the selection criteria]
]