---
title: "More About Function Returns `r emo::ji('dollar')` " 
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---


```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8, fig.height = 6}
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center")

options(htmltools.dir.version = FALSE)

library(xaringanthemer)
library(xaringan)
library(tidyverse)
library(tidyverse)
library(flair)

style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)
```

---
# Conditional returns

Maybe you want to return different results in different situations

```{r even, include = FALSE}
even_or_odd <- function(x) {
  
  if (x %% 2 == 0) {
    
    return("It's even!")
    
  } else {
    
    return("It's odd.")
    
  }
  
  
}

```

```{r, echo = FALSE}
decorate("even") %>%
  flair("x %% 2 == 0") %>%
  flair("It's even!", background = "green") %>%
  flair("It's odd.", background = "pink")
```

---
# Errors

```{r}
add_something <- function(x, something = 2) {
  
  if (!is.numeric(something)) {
    
    stop("Please enter a number!")
    
  }
  
  x + something
  
}
```

---
# Errors
```{r, error = TRUE}
add_something(5, something = "bob")
```

---

class: center, middle

# Debugging

---

```{r}
fibonacci <- function(start, len) {
  
  fib <- vector()
  
  for (i in 1:len) {
    
    fib[i + 1] <- fib[i] + fib[i - 1]
    
  }
  
  return(fib)
  
  
}
```

---
# Debugging tricks

## `print()`

## `browser()`

## `debugonce()`

(Try it.)


---

# Testing

We Only Need to Change the Code in One Place: `standardize()`

```{r testing, include = FALSE, eval = FALSE}
standardize <- function(data) {
  deviations <- data - mean(data, na.rm = TRUE)
  newdata <- deviations / sd(data, na.rm = TRUE)
  return(newdata)
}

testdata <- c(2, 4, 3, 9, NA, 4, 6)
standardize(testdata)
```

```{r, echo = FALSE}
decorate("testing") %>%
  flair("na.rm = TRUE")
```

---
```{r iris2, include = FALSE}
myiris <- iris

myiris$Sepal.Length <- (myiris$Sepal.Length - mean(myiris$Sepal.Length, na.rm = TRUE)) / sd(myiris$Sepal.Length, na.rm = TRUE)
myiris$Sepal.Width <- (myiris$Sepal.Width - mean(myiris$Sepal.Length, na.rm = TRUE)) / sd(myiris$Sepal.Width, na.rm = TRUE)
myiris$Petal.Length <- (myiris$Petal.Length - mean(myiris$Petal.Length, na.rm = TRUE)) / sd(myiris$Petal.Length, na.rm = TRUE)
myiris$Petal.Width <- (myiris$Petal.Width - mean(myiris$Petal.Width, na.rm = TRUE)) / sd(myiris$Petal.Width, na.rm = TRUE)
```

```{r, echo = FALSE}
decorate("iris2") %>%
  flair("na.rm = TRUE")
```

---

# Print versus return


```{r}
even_or_odd <- function(x) {
  
  if (x %% 2 == 0) {
    
    return("It's even!")
    
  } else {
    
    return("It's odd.")
    
  }
  
  
}

bob <- even_or_odd(7)

bob

```

---
# Print versus return


```{r}
even_or_odd <- function(x) {
  
  if (x %% 2 == 0) {
    
    cat("It's even!")
    
  } else {
    
    cat("It's odd.")
    
  }
  
  return(x)
  
  
}

bob <- even_or_odd(7)
bob

```
