---
title: "Practice Activity 8 -- Merge conflicts"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

This activity will give you a taste of what working collaboratively in Github 
looks like. 


# Set-up

I believe learning about merge conflicts is best done in small groups! I want
for you to assign each group member a number, since you will be referencing it 
as you work through this activity. 


# Creating a Repo

**Member 3**: 

- Create a new Github repository titled "stat-331-PA8"
- Click on the "Settings" tab
- Click on "Manage access" 
- Click on "Invite a collaborator" 

Add your other group members to the repository using their username or email


# Accessing the Repo

**All other Members** (e.g. 1, 2, 4, and 5): 

- Verify repository invite in your email
- Open the repository in Github


# Cloning the Repo

**Every** member: 

- Clone the repository into a new RStudio project
  * Copy the HTTPS address from the repo
  * Click on "New project" in RStudio
  * Choose Version Control"
  * Choose "Git"
  * Paste the HTTPS address in the repository address line
  * Navigate to your Stat 331 folder to save your folder somewhere that makes 
  sense
  * Open the project! 
  
  
# Pulling Changes from the Repo

Take turns in completing the exercise, only one member at a time:

- **Member 1**: 
  * Create a new RMarkdown file (using the standard template)
  * Title the document "Practice Activity 8" 
  * Save the document as `PA8.Rmd`
  * Knit the document 
  * Commit **both** the `PA8.Rmd` and `PA8.html` files with an explanatory
  message
  * Push the changes to the repository
  
**All other members:** Pull the changes that were made! 

# Pushing Changes & Not Pulling 

- **Member 2**: 
  * Change the author name in the document to have everyone's *first* names
  * Knit the document
  * Commit the changes
  * Push the changes 
  
**All other members:** Do not pull the changes that were made! 


# Making The Same Changes

- **Member 4** (or 3 if there are only three group members): 
  * Change the author name in the document to have everyone's first **and** last 
  names. 
  * Knit the document
  * Commit your changes 
  * Push your changes

**You will get an error!** 

  * Pull the changes from the repo
  * Review the document with the merge conflict
  * Resolve the conflict with the preferred change
  * Commit your changes
  * Push the changes to the repository 
  
# Making Different Changes

- **Member 5** (or 1 if there are only three group members): 

  * Change the plot of `temperature` and `pressure` (`plot(pressure)`) to use 
  `ggplot()` rather than `plot()`
  * Knit the document
  * Commit your changes
  * Push your changes 
  
**You will get an error, read it, and pull.** 

No merge conflicts should occur. Now push your changes.


# Making the Same Changes (Again)

- **Member 3**:

  * Change the plot of `temperature` and `pressure` (`plot(pressure)`) to use 
  `ggplot()` rather than `plot()`
  * Specify x- and y-axis labels 
  * Knit the document 
  * Commit your changes
  * Push the changes to the repository
  
**You will get an error.**

  * Pull the changes from the repo
  * Review the document with the merge conflict
  * Clear the merge conflict by choosing the correct/preferred change
  * Commit your changes 
  * Push you changes
  

# Final Document 

**All members:** Pull, and observe the changes in your document.


# Submission

How does Git mark the start and end of lines with a merge conflict? Specifically, 
I want the characters, not the commit number. 


