---
title: "Rubric for Oral Exams"
output:
  html_document: default
  pdf_document: default
---

Score   | Demonstration
--------|--------------
4       | __Excellent__ -- Outstanding ability to articulate the concepts covered in the exam, with comprehensive and thoughtful understanding of the content of the assessment. Few if if any errors occur. Any errors that do occur are minor and do not cloud the understanding articulated during the exam.  
        |     
3       | __Good__ -- Ability to articulate the central concepts covered in the exam, but several errors may occur during the assessment. These errors, however, do not cloud the central concepts of the assessment. 
        |    
2       | __Fair__ -- Limited ability to articulate the concepts covered in the exam, explanations contain inconsistencies and demonstrate limited understanding of the content.  
        |    
1       | __Poor__ -- Little to no articulation of concepts covered in the exam, numerous inconsistencies and errors occur and demonstrate little to no understanding of the content. 
        |    
0       | __No credit__ -- Inability to present any understanding of topics covered in exam. 


</br>

## Questions 

</br>

**Question 1** 

> Describe how you chose your "best" model from Part Three. If you used a 
function to iterate through a set of possible models, walk me through what the 
function does. If you did not use iteration, describe to me how you would 
transform your method to use iteration instead. 

**Question 2** 

> Suppose you are helping another student with their R code for a research project 
they are working on. Going through their code, you notice they seem to copy and
paste the same process multiple times in lots of different locations. What
changes would you suggest they make? Why do you think these changes are
important?

## Scoring 

**Note that each question is weighted equally in the final grade.** 

- 4, 4, (A+) 
- 4, 3 or 3, 4 (A)

- 3, 3 (B)
- 4, 2 or 2, 4 (B-)

- 3, 2 or 2, 3 (C+)
- 2, 2 (C)

- earning a 1 on either question (at most a D+)
- earning a 0 on either question (F)