---
title: "Introduction to Reading in Data"
format: 
  html: 
    self-contained: true
    theme: minty
    fontsize: 1em
    mainfont: sans-serif
    number-sections: true
    number-depth: 2
    code-block-bg: "#76b5c5"
    highlight-style: monochrome
editor: visual
execute: 
  echo: true
  eval: false
  include: true
resources: 
  - data_import_practice.qmd
  - Ages_Data.zip
---

```{r}
#| include: false
library(tidyverse)
library(flair)
```

`r emo::ji("play button")` Watch Videos: 14 minutes

`r emo::ji("book")` Readings: 15-20 minutes

`r emo::ji("computer")` Activities: 30 minutes

`r emo::ji("check")` Check-ins: 1

# Loading Data Into R

## Where does my data live?

`r emo::ji("play button")` [Required Video: Data Locations and the {here} package (8 minutes)](https://www.youtube.com/watch?v=jvWwrELLEw8)

## How do I load my data?

`r emo::ji("book")` [Required Reading: Data Import](https://r4ds.had.co.nz/data-import.html)

`r emo::ji("play button")` [Required Video: Loading Data (6 minutes)](https://www.youtube.com/watch?v=Kp4tJYCAvUs)

`r emo::ji("computer")` Download the [Ages_Data.zip folder](Ages_Data.zip) and
the [data_import_practice.qmd](data_import_practice.qmd) files. Save these files
in your Stat 331 folder, possibly inside a subfolder named "Activities" or
"Week 2".

::: {.callout-tip}
## Extracting zip folders
You will need to **extract** the contents of the `ages.zip` file, that means you will need to uncompress the files from the folder for RStudio to know where to get the data from.
:::

Now, open your STAT 331 RStudio Project. Next, open the
`data_import_practice.qmd` file and write the code necessary to carry out the
following tasks:

1.  Read in the dataset `ages.csv`.
2.  Read in the dataset `ages_tab.txt`
3.  Read in the dataset `ages_mystery.txt`
4.  Read in the dataset `ages.xlsx`
5.  Both `read.csv()` and `read.table()` have an optional argument called `stringsAsFactors`. Figure out what this does.
6.  Find a way to use `read_csv()` to read `ages.csv` with the variable "Name"
as a factor and "Age" as a character.

------------------------------------------------------------------------

## `r emo::ji("check")` Check-in: Loading Data

**Question 1** -- Which functions could you use to load in the ages.csv dataset?

-   `read_csv()`
-   `read_delim()`
-   `read_tsv()`

**Question 2** -- Which functions could you use to load in the ages_tab.txt dataset?

-   `read_tsv()`
-   `read_csv()`
-   `read_delim()`

**Question 3** -- What `delim` option do you need to declare to load in the ages_mystery.txt dataset?

-   `delim = " "`
-   `delim = "|"`
-   `delim = "\t"`

**Question 4** -- **True or False** -- The `read_csv()` function automatically converts strings (character variables) to factors
