---
title: "Lab 3: Hip-Hop Lyrics"
author: ""
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    css: styles.css
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE,eval=FALSE)

```

## Instructions and Tips

Please submit an HTML document created using R Markdown.

* The first chunk of your R Markdown document should be to set the
*global chunk options*.

* The second chunk of your R Markdown document should be to
*declare your libraries* (probably only `tidyverse` for now).

* Make sure you address **all the questions** in these instructions.

* If a question requires **any** type of calculation, 
**you should provide code for your answer!**

* I have provided hints about functions that might be useful to you.  You are
**not required** to use these functions.

* You may have to Google to solve some of these!

* Be sure to **save** your work regularly (*Ctrl/Cmd+S* or *File > Save* or the
floppy disk icon)

* Be sure to **knit** your file every so often, to check for errors and make
sure it looks nice.

    + Make your R Markdown document does not contain `View(dataset)` or `install.packages("package")`, both of these will prevent knitting.
    
    + Check your R Markdown document for moments when you looked at the data by
    typing the name of the data frame.  Leaving these in means the whole dataset
    will print out!
    
    + If all else fails, you can set your *chunk option* or *global option* to
    `error = TRUE`, which will allow the file to knit even if errors are present.
    
---


## The dataset

The data set "hiphop" contains results from a study conducted by a linguist at
the University of Minnesota.  The researcher was interested in predicting
musical taste based on familiarity with African American English (AAE).  168
subjects participated in the study, and each was asked to define 64 different
AAE terms.  The definitions given were used to create a "familiarity" score for
each subject for each term.  This score quantifies how well the subject knew the
term on a scale of 1-5 (1 = not at all, 5 = very well).  Before tackling the
problems, **study the information on the following website**, which includes a
description of each variable:

[http://conservancy.umn.edu/bitstream/handle/11299/116327/5/explanationAAEHiphopChesley.txt](http://conservancy.umn.edu/bitstream/handle/11299/116327/5/explanationAAEHiphopChesley.txt)

You can download the data [at this Dropbox link](https://www.dropbox.com/s/5d8fwxrj3jtua1z/hiphop.csv?dl=0).

---

## Assignment

### Summary

#### 1. 

Provide a brief overview (2-4 sentences) of the dataset. (It is always good
practice to start an analysis by getting a feel for the data and providing a
quick summary for readers.) You do **not** need to show any source code for this
question, although you probably want to use code to get information.

#### 2. 

What are the rows of this dataset?  It is __not__ one person per row! 


#### 3. 

Missing values for some of the variables were replaced with other values. How 
were missing values replaced? What do you believe are some benefits and
drawbacks of doing this? 


#### 4. 

Clean the dataset in whichever ways you see fit.  This might mean adjusting 
*variable type*, for example from `character` to `factor`, or dealing with
missing data.


#### 5. 

How many unique AAE words were studied in this dataset?

Helpful functions: `distinct()`, `count()`


#### 6. 

Make a new variable that re-categorizes `ethnic` into only two groups, "white"
and "non-white", to simplify your data.

Helpful functions: `mutate()`, `if_else()`


#### 7. 

What are the demographics of the people in this study?  Investigate the
variables `sex`, `age`, and `ethnic` and summarize your findings in 1-3 complete
sentences.  

*Hint: You'll need to first manipulate your data to have each person represented
only once.*

Helpful functions:  `select()`, `distinct(___, .keep_all = TRUE)`,
`count()`,  `summary()`


#### 8. 

Make at least two plots to display the demographic information of the subjects
in this study.  You do not need to discuss these plots, but make sure they are
appropriate to the data types and have informative titles and axis labels.

Functions:  `ggplot()`, `geom_histogram()`, `geom_boxplot()`, `geom_bar()`,
`geom_col()`, `facet_wrap()`, `labs()`


### Familiar words

For each demographic group listed below, determine which word(s) in this study
was(were) the most **and** least familiar on average.

a. People below the age of 20
b. Non-white women
c. White men above the age of 30

Helpful functions: `filter()`, `arrange()`, `desc()`, `slice_max()`,
`slice_min()`

### Study Subjects


A joke among the [Tidy Tuesday](https://www.tidytuesday.com/) community is that
Justin Bieber was one of the
subjects in this study. Bieber, a white male, from a relatively small town
(10,000-60,000 people) in Ontario would have been 17-23 at the time of the
study.

Determine which subject you believe is secretly Bieber, justify your answer.

*Hint: Refer again to the dataset description.  There is another clue about Bieber's identity.*

---

## Challenge

### Published Comparisons

*(Turn your challenge in as a separate html file from the lab.)*

In the published article ([You Know What It Is: Learning Words through Listening to Hip-Hop](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0028248)), 
the author presents a series of comparisons about the variables which most 
explain an individual's familiarity with African American English (AAE). 

Let us instead compare the number of artists participants reported
liking for each genre. Specifically, you will determine which music genre most
differentiates each of the demographic groups provided.  That is, which genre
had much higher average (mean or median) reported artists in one group than the
other.

a. Male versus Female
b. White versus Non-White

*Hint: You might find it helpful to first create a new dataset with only the 
variables you are interested in!*

Helpful functions: `select()`, `group_by()`, `summarize()`, `across()`

**In your Think Out Loud Recording you will be expected to explain your thought process and the code you produced.**


### Study Design Critique

Myself, members of the Tidy Tuesday community, and previous 331 students have
voiced concerns regarding the design and social context of this study. 

Re-read the [variable description (link)](http://conservancy.umn.edu/bitstream/handle/11299/116327/5/explanationAAEHiphopChesley.txt) to see how participants were recruited for participation in this study. 

You are welcome to read additional details regarding aspects of the study in the
published paper:
[You Know What It Is: Learning Words through Listening to Hip-Hop](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0028248)


>
> Based on the design of this study and its context (African American English), 
> what are **at least two** concerns you have?
>
