---
title: "Rubric for 331 Midterm Oral Exams"
output:
  html_document: default
  pdf_document: default
---

Score   | Demonstration
--------|--------------
4       | __Excellent__ -- Outstanding ability to articulate the concepts covered in the exam, with comprehensive and thoughtful understanding of the content of the assessment. Few if if any errors occur. Any errors that do occur are minor and do not cloud the understanding articulated during the exam.  
        |     
3       | __Good__ -- Ability to articulate the central concepts covered in the exam, but several errors may occur during the assessment. These errors, however, do not cloud the central concepts of the assessment. 
        |    
2       | __Fair__ -- Limited ability to articulate the concepts covered in the exam, explanations contain inconsistencies and demonstrate limited understanding of the content.  
        |    
1       | __Poor__ -- Little to no articulation of concepts covered in the exam, numerous inconsistencies and errors occur and demonstrate little to no understanding of the content. 
        |    
0       | __No credit__ -- Inability to present any understanding of topics covered in exam. 


</br>

## Scoring 

__A: 4__  

__B: 3__

__C: 2__

__D: 1__

__F: 0__
