---
title: "Why write a function `r emo::ji('question')`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---


```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8, fig.height = 6}
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center")

options(htmltools.dir.version = FALSE)

library(xaringanthemer)
library(xaringan)
library(tidyverse)


style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)
```


<!-- # Your turn -->

<!-- Write a function called `times_seven()` which takes a single argument and multiplies by 7.  -->

<!-- -- -->
<!-- *Sneak Preview* What happens when you run this? -->

<!-- ```{r, eval = FALSE} -->
<!-- my_vec <- c(7, 8, 9) -->

<!-- times_seven(my_vec) -->
<!-- ``` -->


<!-- What about this? -->

<!-- ```{r, eval = FALSE} -->
<!-- times_seven(mtcars) -->
<!-- ``` -->


---

# BUT WAIT

Perhaps you observed that we haven't *completely* eliminated copy-pasting!

```{r}
stdize_column <- function(dat, variable) {
  dat[[variable]] <- standardize(dat[[variable]])
  return(dat)
}

iris <- iris %>%
  stdize_column("Petal.Length") %>%
  stdize_column("Petal.Width") %>%
  stdize_column("Sepal.Length") %>%
  stdize_column("Sepal.Width")

```

--

Stay tuned...

---