---
title: "Challenge 4 -- Grading Guide"
output: html_document
---

# Joining the Datasets

- Acquire a dataset on CA housing prices -- 3 points

  * Make your own dataset by hand entering prices -- 2 points
  * Obtain a dataset from a source with no citation -- 2 points
  * Obtain a dataset with single values for each year -- 2.5 points
  * Obtain a dataset from a reputable source with values for different years -- 
  3 points

- Joining the datasets -- 2 points

# Making Your Case

- Produce a visualization -- 2 points

  * Visualize the relationship between housing prices and avocado prices across
  different cities -- 3 points
  * Visualize the relationship between housing prices and avocado prices across
  different cities on **different** plots -- 2 point
  * Visualize relationship between housing prices and avocado
  prices **without** accounting for location -- 1 point

- Display summary statistics for housing prices across three regions -- 1 point
  
- Make an argument as to why / why not avocados affect millennial' ability 
to purchase a house in CA -- 1 point