---
title: "Lab 4 Grading Guide"
output: html_document
---

</br>

**If there is no response to a question a score of 0 is awarded.**

**If code outside of the _R for Data Science_ book is used, a citation must be 
included. If no citation is included, the question is awarded a 0.**

---

# RMarkdown Report 

## Report Formatting

**4**: The report has the following, 

- Easy to locate headers / titles for question numbers
- No warnings from code
- No messages from code
- No output of data previews

**3**: The report includes a preview of the data (e.g., `glimpse(avocado)`)

**Redo if above conditions are not met**

</br>

## Code Formatting 

**4**: Code formatting adheres to the tidyverse styling guide. At a bare
minimum, the code has the following:
  
  * spaces around `=` signs 
  * spaces after `,`s
  * new lines after `+`s
  * new lines after `%>%`s
  * no lines of code that wrap across multiple lines

**3**: No more than two occurrences of code formatting which does not adhere to
styling guide

**Redo if above conditions are not met**

</br>

## Reading in Data

**4**: Reads data in with the `here()` function 

**Redo: If uses relative or full path to read in the data**

---

# Exercises

## Problem 1

**4**: Must have the following,

1. context of data (**Hass** avocado sales)
2. duration of data (2015 to 2018)
3. description of variables (date of sale, price of avocado, region of sale,
  type of avocado, size of avocado)

**3**: Has components 1 & 2, describes some variables but not all

**Redo if the above conditions are not met**

</br>

## Problem 2

**4**: Must have the following,

1. Uses `rename()`, `mutate()`, or `transmute()` to convert PLU variable names
(`4046`, `4225`, `4770`) to variables related to **size** of avocado:

  - `4046 = small_avocado` (or similar)
  - `4225 = large_avocado` (or similar)
  - `4770 = XL_avocado` (or similar)

2. Uses `filter()` to drop `"TotalUS"` from dataset

**Redo if above conditions are not met**


</br>

## Problem 3

**4**: Must have the following,

1. A dataset with the following major regions defined: Plains, Midsouth, 
West, SouthCentral, Northeast, Southeast, GreatLakes

2. A region-level dataset produced with a `semi_join()`

3. `filter(type == "organic", year == 2017)` (could be two calls to `filter()`)

4. `group_by(region)`

5. Uses `summarize()` to find the `sum(Size_Small))`

6. Names the summary statistic inside of summarize()` (e.g., 
`summarize(tot_small_bags = sum(Size_Small)`)

6. Uses `slice_max()` to grab the maximum of the summarized variable
(`tot_small_bags`)


**3**: 

- Satisfies criteria 1-5, but does not name the summary and / or use 
`slice_max()` to grab the max

*OR*

- Satisfies criteria 2-5 but includes regions beyond those defined as "major"

**Redo if above conditions are not met**

</br>

## Problem 4

**4**: Must have the following,

1. Uses the `separate()` function to create three new columns: Year, Month, and 
Day

2. `group_by(Month)` 

3. Uses `summarize()` to find the `sum('Total Volume')`

4. Names the summary statistic inside of summarize()` (e.g., 
`summarize(tot_sales = sum('Total Volume')`)

5. Uses `slice_max()` to grab the maximum of the summarized variable
(`tot_sales`)

**3**: Satisfies criteria 1-3, but does not name the summary and / or use 
`slice_max()` to grab the max

**Redo if above conditions are not met**

</br>

## Problem 5

### Data Summary 

**4**: Must have the following,

1. A dataset defined with regions to exclude. These can be *all* of the regions
to exclude (major regions, minor regions, and states), or they could be only 
the minor regions and states not included in the previous "major regions" 
dataset. 

- Additional regions to exclude: California, WestTexNewMexico,
NorthernNewEngland, SouthCarolina

2. A metro-level dataset produced with one or two `anti_join()`s

3. The top 5 region's mean avocado sales found using:

- `group_by(region)`
- `summarize(avgtotvol = mean('Total Volume'))`
- `slice_max(n = 5, avgtotvol)` 

**3**: Satisfies criteria 1-3, but does not name the summary and / or use 
`slice_max()` to grab the max

**Redo if above conditions are not met**

### Data Visualization

**4**: Must have the following,

1. The top 5 metro-regions are `semi_join()`ed from previous data summary code

2. The metro-regions are plotted so their labels do not overlap

3. The x- and y-axis labels are renamed to describe what is being plotted

**3**: 

- Satisfies criteria 1 & 2 but does not create new axis labels

*OR*

- Satisfies criteria 2 & 3, but uses a `filter()` to obtain only the top 5 
metro-regions

**Redo if above conditions are not met**

</br>

---

# Reshaping

## Problem 6

### Data Summary 

**4**: Must have the following,

1. A dataset is defined with California regions

2. The California dataset is used to `semi_join()` with the `avocado` dataset

3. `group_by(region, type)`

4. Uses `summarize()` to find the `mean(AveragePrice)`

5. Uses `pivot_wider()` to relocate the `type` of avocados to columns, filled 
with the values found in the `summarize()` step

6. Uses `mutate()` to create a column of the differences in prices between 
the avocado types 

</br> 

**3**: Satisfies criteria 3-6 but does not use a `semi_join()` to extract CA
cities

**Redo if above conditions are not met**


### Data Visualization

**4**: A visualization must have the following,

1. The distribution of average avocado prices (e.g., boxplots, density plots)

2. Differentiation between organic and conventional avocados (as a `fill`
or as an axis)

3. Differentiation between cities (as a `fill` or as an axis)

4. x- and y-axis labels which to describe what is being plotted

**3**: 

- Satisfies criteria 1 - 3 but does not create new axis labels

*OR* 

- Uses `facet_wrap()` to differentiate between type of avocado or CA city

**Redo if above conditions are not met**

</br>

## Problem 7

**4**: Must have the following,

__Before the Plot__

1. `group_by(region, type)`
2. `summarize(across(.cols = [NAME_OF_SIZE_VARIABLES], .fns = mean))`
3. `pivot_longer([NAME_OF_SIZE_VARIABLES], names_to = "Size", values_to = "Mean_Sold")`
4. releveling of the `Size` variable to be ordered Small, Large, Extra Large
(can use `factor()` or `fct_relevel()`)

__To Create the Plot__

5. `ggplot(aes(x = region, y = Mean_Sold, fill = Size))` -- names of `Mean_Sold`
and `Size` depend on `pivot_longer()` step
6. `geom_col(position = "fill")`
7. `facet_wrap(~type)`
8. Change axis labels to: `x = "Region of CA"`,
`y = "Proportion of Mean Avocados Sold"`, `fill = "Avocado Size"`

If 4 was not done above, a theme was used to reverse the direction of the colors

</br>

**3**: Uses multiple calls to `summarize()` instead of using `across()`

**Redo if above conditions are not met**

