---
title: "Getting Fancy -- Arranging Some Data"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include=FALSE}
library(xaringanthemer)
library(xaringan)
library(showtext)
library(fontawesome)
library(tidyverse)
library(flair)

style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)
```

```{r, echo = FALSE, message = FALSE}
cereals <- read_csv("../practice/cereals.csv") %>% 
  mutate(type = as_factor(type), 
         mfr = as_factor(mfr))
```

# Ordering

Verb: `arrange()`

We **arrange** the dataset in order of a particular variable.

```{r}
penguins %>% 
  arrange(body_mass_g)
```

---

## Related: `top_n`

```{r}
penguins %>%
  top_n(3, body_mass_g)
```

---

# Quick check in!

Remember,

```{r, eval = FALSE}
penguins %>%
  top_n(3, body_mass_g)
```

is the same as

```{r, eval = FALSE}
top_n(penguins, 3, body_mass_g)
```

or

```{r, eval = FALSE}
top_n(x = penguins, n = 3, wt = body_mass_g)
```

4. The cereals in the dataset are ordered from most to least calories per cup.

