---
title: "It's a Party Now -- Making Groups"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include=FALSE}
library(xaringanthemer)
library(xaringan)
library(showtext)
library(fontawesome)
library(tidyverse)
library(flair)

style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)
```

```{r, echo = FALSE, message = FALSE}
cereals <- read_csv("../practice/cereals.csv") %>% 
  mutate(type = as_factor(type), 
         mfr = as_factor(mfr)) %>% 
  rename(temp = type)
```

.larger[Making Groups]

Verb: `group_by()`

Separating a **categorical** variable into its different levels. 

```{r group, echo = FALSE, eval = FALSE}
group_by(cereals, temp)
```


```{r, echo = FALSE}
decorate("group", eval = FALSE) %>% 
  flair("group_by") 
```

---

.larger[A grouped dataset?]

```{r}
group_by(cereals, mfr)
```

---

.larger[A friend!]

`group_by()` is almost always paired with `summarize()` 

</br>
<center>

.larger[How?]

---

.larger[Option #1: Nesting]

```{r}
summarise(
  group_by(cereals, mfr), 
  mean_cal = mean(calories)
)
```

---

.bitlarger[Option #2: Intermediate Variable]

```{r}
groups <- group_by(cereals, mfr)

summarise(groups, mean_cal = mean(calories))
```

---

.larger[Option #3: The pipe]

```{r}
cereals %>% 
  group_by(mfr) %>% 
  summarise(mean_cal = mean(calories))
```

