---
title: "The Final Step in Efficient Iteration"
author: Stat 331
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---


```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8, fig.height = 6}
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center")

options(htmltools.dir.version = FALSE)

library(xaringanthemer)
library(xaringan)
library(tidyverse)
library(flair)
library(glue)
library(purrr)
library(palmerpenguins)

style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)


standardize <- function(data) {
  stopifnot(is.numeric)
  deviations <- data - mean(data, na.rm = TRUE)
  newdata <- deviations / sd(data, na.rm = TRUE)
  return(newdata)
}
```

.larger[The best option: the `map` family] 

.pull-left[
- `map_chr()`
- `map_lgl()`
- `map_int()`
- `map_dbl()`
]

.pull-right[
- `map2_chr()`
- `map2_lgl()`
- `map2_int()`
- `map2_dbl()`
- `pmap()`

]

---

.larger[`map_dbl()`]

```{r}
penguins %>% 
  select(bill_length_mm:body_mass_g) %>% 
  map_dbl(mean, na.rm = TRUE)

```

---

.larger[`map_dbl()`]

.pull-left-wide[
```{r}
penguins %>% 
  map_int(~ sum(is.na(.x)))

```
]

--

.pull-left[
- Note the `~` in front of the function!
]

</br>
</br>

.pull-right[
- Note the `.` before the `x`!
]
