---
title: "Lab 1 Grading Guide"
output: html_document
---

# 1. Changing the YAML

**4**  

- The title of the document should be "Lab 1"

- The author of the document should be their name

**Redo if not met** 

</br> 

# 2. Changing the opts chunk

**4** 

- added `fig.align = "center"` *inside* the `opts_chunk$set()` 
- added `message = FALSE` *inside* the `opts_chunk$set()`

Should look like:

```{r, eval = FALSE, echo = TRUE}
opts_chunk$set(echo = TRUE, 
               fig.align = "center", 
               message = FALSE)
```

**3** 

- If they set `warning = FALSE` instead of `message = FALSE`

**Redo if not a 4 or 3** 

</br> 

# 3. Add a New Section with Content

**4**

- Adds a section named **Cars Dataset**

- In the section states:

  * "This dataset contains information about "speed of cars and the distances
  taken to stop. The data were recorded in the 1920s."
  * "It has 50 rows and 2 variables.*
  
**3**

Meets all criteria for a 4 but statement doesn't include information on when
the data were collected. 

**Redo if not a 4 or 3** 

</br> 

# 4. Modify the Provided Plot

**4** 

- x-axis label (temperature) includes "deg C" in title
- y-axis label (pressure) includes "mm" in title

**Redo if criteria not met**

</br>

# 5. Creating a Code Chunk

**4** 

- Document contains *1* code chunk doing the following: 

  * Extract the distance column of the `cars` dataset and save it into a new
  object named `dist`. 
  
- Document contains *1* or *2* code chunks doing the following: 

  * Plot the distribution of the stopping distances (`dist`).
  * Plot the relationship between the stopping distance (`dist`) and speed
  (`speed`).

- Distribution of stopping distances must be plotted with either a *histogram* 
or a *density* plot

- Plots created have axis labels with units

*Note:* If they use `ggplot()` to plot the distribution of `dist`, then it is
okay if they don't use the `dist` variable that is the vector of extracted
distances. But they must have the code that extracts `dist` regardless of
whether they use it for their plot. 


**3**

- Document contains *1* code chunk 
- Plots created have axis labels with units


**Redo if not a 4 or a 3**

</br>

# 6. Commenting on Plots

**4** 

- includes at least *two* aspects of the plots they wish they could improve

**Redo if criteria not met**







